version: '3'
services:

  frontend:
    build: ./
    ports:
      - "80:80"
    volumes:
      - ./public/assets/images/figures:/app/assets/images/figures
      - ./public/assets/images/models:/app/assets/images/models

